### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by bahaaza** [namecheap/go-namecheap-sdk#36]
Hey, I wanted to ask if this repo is still maintained, if yes, I will proceed with my question.

**Comment by adamdecaf** [comment]
I transferred the repository to Namecheap for them to maintain. Do you have an issue / feature request?

**Comment by bahaaza** [comment]
I had an issue with the following repo https://github.com/jamesgoodhouse/cert-manager-webhook-namecheap which uses your SDK, but the bug ended in the repo itself and not your SDK, it's written in go and it was not been updated for two years. there are a lot of missing integration tools for Namecheap, eventually, I gave up and transferred my domain to Cloudflare.

**Comment by vetal2409** [comment]
Hello! 

Thanks for your patience! We recognize there has been a period of paused activity from our side, and we truly appreciate your understanding during this time.

We are now resuming support and development for this repository. Feel free to create an issue with your bug or feature request and we will try to process it ASAP.
