### ISSUE TITLE
Support for "domains-ns" API Endpoints - in order to support "namecheap_nameserver" resource in terraform provider

### ISSUE THREAD

**Issue by brookatlas** [namecheap/go-namecheap-sdk#38]
Question:  I would like to add support myself for the following endpoints:
 -- registration of a new nameserver: https://www.namecheap.com/support/api/methods/domains-ns/create/
 -- removal of existing nameserver: https://www.namecheap.com/support/api/methods/domains-ns/delete/
-- get info of existing nameserver: https://www.namecheap.com/support/api/methods/domains-ns/getinfo/
 -- update of existing nameserver: https://www.namecheap.com/support/api/methods/domains-ns/update/
 
 this is in order to support this issue: https://github.com/namecheap/terraform-provider-namecheap/issues/76
 
 I have no problem forking, updating the code and doing whatever it takes.
 
 However, this repo seems Un-maintained, And I would like to get some validation from some of the code owners that this repo is still alive, before going forward and putting in the work.
 
 Please ping me in the comments, if there is still anybody reviewing code here.
 
 thanks :)

**Comment by vetal2409** [comment]
Hello!

Thank you for your patience! We recognize that there has been a period of paused activity on our side, and we truly appreciate your understanding during this time.

We are now resuming support and development for this repository. I've just created a task in our internal system to address your feature request. We will tackle this task as soon as we fix all the critical bugs related to this repo and the Terraform provider.

Feel free to create PRs (Pull Requests) to speed up development. We would really appreciate it.

**Comment by brookatlas** [comment]
as you may see, I opened a PR for the "domains.ns.getInfo" method. I made sure to follow the existing style in the project.

Please give it a look in your time. once it gets approved, I will open matching pull requests for all of the other endpoints(better to start with first review to see how you look over things).

https://github.com/namecheap/go-namecheap-sdk/pull/39

**Comment by brookatlas** [comment]
Is this active? Still waiting for assignment/review.

**Comment by vetal2409** [comment]
Thanks a lot! 
I've just published a new tag v2.2.0

**Comment by brookatlas** [comment]
opened PR for updating nameservers:
https://github.com/namecheap/go-namecheap-sdk/pull/42

**Comment by vetal2409** [comment]
@brookatlas thanks a lot!
