### ISSUE TITLE
Failure when NS records are present

### ISSUE THREAD

**Issue by AyKarsi** [namecheap/go-namecheap-sdk#9]
Error I recieved was:
`Invalid record type, allowed types="A", "AAAA", "CNAME", "MX", "MXE", "TXT", "URL", "URL301", "FRAME"`

Stumbled on this while trying to create a new A Recored using the terraform provider. 
After removing NS records from my domain it worked. 
I can image that this can be  problem for others..

**Comment by adamdecaf** [comment]
Were you trying to set NS records with `namecheap_record`? I've had to use `namecheap_ns` to set those.

**Comment by ifree92** [comment]
@AyKarsi I trust you had an issue with using `namecheap_record` resource to add nameservers instead of `namecheap_ns`.

At the moment I'm closing the issue. We have made a complete project refactoring #24
